### ISSUE TITLE
Feature request: Any plan for supporting Lidar ?

### ISSUE THREAD

**Issue by TheEhsanSarshar** [BabylonJS/BabylonReactNative#131] opened 2020-12-04 16:17 UTC
first of all Thanks for this amazing library. that's really epic.
is there any plan to support Lidar for Babylon react native or maybe Babylon native at all

**Comment by ryantrem** [comment] 2020-12-04 16:55
When you say "Lidar," I think you mean Lidar on iOS devices via ARKit. Assuming that is the case, then the answer depends on what you mean.
1. Lidar makes tracking more robust, without any code changes, so we get this for free today.
1. Lidar can provide raw environment information, like meshes for real world surfaces. We have work in progress to support this type of thing. We are starting with HoloLens, but designing the APIs in such a way that it should be able to support ARKit Lidar based depth/environment info as well. Changes are required in both Babylon.js and Babylon Native to support this. The first round of changes in Babylon.js are already complete. See https://github.com/BabylonJS/Babylon.js/pull/9307. The first round of changes to Babylon Native are in flight. See https://github.com/BabylonJS/BabylonNative/pull/476. Again, these changes are initially being implemented to support HoloLens, but we are keeping ARKit Lidar in mind, and would welcome any contributions in this space!
1. Lidar can also enable occlusion scenarios (e.g. real world objects occluding virtual objects). We have an issue tracking this, but haven't started digging into it at all. See https://github.com/BabylonJS/BabylonReactNative/issues/39. This is another area we would welcome contributions.

**Comment by ryantrem** [comment] 2020-12-06 02:22
FYI @chrisfromwork

**Comment by EhsanSarshar** [comment] 2020-12-06 06:07
@ryantrem Thanks alot for the response.
I am not sure which one of the options it's belong too.
 I was looking for a scenario that Digital AR objects can hide behind a wall or respect other actual objects in the room. and I think it's possible with Lidar

**Comment by ryantrem** [comment] 2020-12-06 22:38
Yes, what you describe is occlusion, and is tracked by issue #39.

@rgerd added an occlusion shader to Babylon.js recently (https://github.com/BabylonJS/Babylon.js/pull/9387), which is one small part of the solution.

There are a number of ways you could contribute:
1. Express your interest by adding a comment to #39 so we can keep a pulse on this issue.
1. Research occlusion support in ARKit (and ideally ARCore), and add what you learn to issue #39 (e.g. is occlusion expressed through some kind of depth/mask texture or what?). I think most of the people currently involved in this project understand that occlusion is a thing we want to do, but I don't think there is much knowledge yet on the details of how occlusion is supported from an ARKit/ARCore API standpoint.
1. If you have C++/ObjectiveC/Java experience, you could prototype occlusion support in Babylon Native.

Since this issue is effectively a duplicate of #39, we will probably go ahead and close out this issue, but keep it linked to #39 for context.

**Comment by chrisfromwork** [comment] 2020-12-14 18:35
We checked in initial scene understanding for UWP/HoloLens today:
https://github.com/BabylonJS/BabylonNative/pull/476

I may have accidentally filed a duplicate issue, but based on PR feedback, I filed the following to bring WebXRMeshDetector support to ARCore/ARKit. @ryantrem let us know if you'd prefer to track with your other issue.
https://github.com/BabylonJS/BabylonNative/issues/542

FWIW, I don't think our team has access to lidar sensors right now. But, the scaffolding/initial setup for ARKit is now all stubbed out in BabylonNative. The work likely involves the following:

1. Update Babylon.js object type definitions to support scene objects supported by ARKit here:
https://github.com/BabylonJS/Babylon.js/blob/b69d1f4094b9b8d4d3488e3cabbc25e4a7dd5ddf/src/LibDeclarations/webxr.nativeextensions.d.ts#L5
2. Update ARKit BabylonNative logic to start reporting scene objects here:
https://github.com/BabylonJS/BabylonNative/blob/e287187c0fa2503f1dde277eaa46534e69ef3a63/Dependencies/xr/Source/ARKit/XR.mm#L1202
3. Update BabylonReactNative to consume these newer Babylon.js/BabylonNative dependencies.

**Comment by ryantrem** [comment] 2021-08-02 19:27
Bullet 1 above is implicit by use of ARKit on an iOS device with lidar, bullet 2 was implemented by @chiamaka-123 in https://github.com/BabylonJS/BabylonNative/commit/00ea35e7dfc7622d25f1bf45d502f4061ad96c63, and bullet 3 is tracked by https://github.com/BabylonJS/BabylonNative/issues/857, so I'm closing this issue.

**Closed by ryantrem** 2021-08-02 19:27 UTC
Labels: question
