### ISSUE TITLE
Huge distortion and mesh disappearances on some Android devices (example - Samsung Galaxy A71)

### ISSUE THREAD

**Issue by star-collector** [BabylonJS/BabylonReactNative#256] opened 2021-07-09 09:43 UTC
**Describe the bug**

On some Android devices character models are transparent. Also, there is huge distortion present. Majority of Android devices render everything just fine, but some particular devices behave like this with BabylonReactNative.

**To Reproduce**
1. Open sample app on Samsung Galaxy A71 - https://github.com/star-collector/babylon-playground
2. Everything is distorted and some models are transparent

**Expected behavior**

Everything renders fine. Character models are non-transparent, there is no distortion of any kind.

**Screenshots**

How 3D scene should look:

![124778012-4ea56180-df49-11eb-8174-c614528692ac](https://user-images.githubusercontent.com/19988178/125058385-e3779e80-e0b2-11eb-968b-6bbe46bf0071.jpeg)

How app looks on Samsung Galaxy A71 and other affected devices:

![photo_2021-07-09_11-45-24](https://user-images.githubusercontent.com/19988178/125058440-effbf700-e0b2-11eb-9219-b4066637a7f5.jpg)

How provided sample app looks on affected devices:

![photo_2021-07-09_12-37-16](https://user-images.githubusercontent.com/19988178/125058456-f4c0ab00-e0b2-11eb-8666-e9af8e9e4238.jpg)

**Other**
 - Platform: Android 10
 - Device: Samsung Galaxy A71

**Comment by ChocoPieLotte** [comment] 2021-07-14 08:58
I also faced the same problem on my galaxy fold

**Comment by CedricGuillemet** [comment] 2021-07-20 14:18
Do you see some errors related to OpenGL in the logcat?

**Comment by star-collector** [comment] 2021-07-20 14:36
> Do you see some errors related to OpenGL in the logcat?

No, there are no errors of any kind. At least, I think so. Just OpenGLRenderer log messages.

<img width="559" alt="Screenshot 2021-07-20 at 17 31 06" src="https://user-images.githubusercontent.com/19988178/126342558-aa3a7304-e133-4261-94c2-5727da4b9705.png">

<img width="569" alt="Screenshot 2021-07-20 at 17 29 39" src="https://user-images.githubusercontent.com/19988178/126342580-203c5cc5-b5a6-4492-a40e-15afd0eca6aa.png">

Also, I checked old versions of `@babylon/react-native` (prior to stencil changes) and the problem occurs with them as well.

**Comment by ryantrem** [comment] 2021-07-20 14:38
What is the OS version on those devices with rendering issues?

**Comment by star-collector** [comment] 2021-07-20 14:39
> What is the OS version on those devices with rendering issues?

Android 10

**Comment by AAAkatov** [comment] 2021-08-02 13:15
@CedricGuillemet @ryantrem @bghgary 
Hi!
We encountered a similar problem on the devices Asus Rog Phone, Samsung А71, Samsung Galaxy Fold 2.
Maybe there is some solution that can be done locally?
Are there any plans to solve this problem?

**Comment by bghgary** [comment] 2021-08-03 00:00
It's difficult to figure out without a repro. We don't have access to many of these devices. It looks like we have Asus Rog Phones so that might work. @AAAKatov @star-collector Can you run `about://gpu` on a browser for phones that repro so that we can try to find phones with similar hardware to try to repro?

**Comment by star-collector** [comment] 2021-08-03 07:27
@bghgary Samsung Galaxy A71:

[gpu.html.pdf](https://github.com/BabylonJS/BabylonReactNative/files/6922108/gpu.html.pdf)

**Comment by ChocoPieLotte** [comment] 2021-08-03 08:00
@bghgary For Asus Rog Phone
[AsusRogPhone.pdf](https://github.com/BabylonJS/BabylonReactNative/files/6922319/AsusRogPhone.pdf)

**Comment by AAAkatov** [comment] 2021-08-03 08:49
@bghgary for Samsung Fold 2
[Samsung Fold 2.pdf](https://github.com/BabylonJS/BabylonReactNative/files/6922803/Samsung.Fold.2.pdf)

**Comment by bghgary** [comment] 2021-08-03 23:11
I checked out an Asus Rog Phone from our devices lab, so hopefully it will repro and then we can try to figure out what is happening.

**Comment by bghgary** [comment] 2021-08-04 22:44
I can't get this sample app to run. I get this error in the metro log:

> error: node_modules\react-native\Libraries\Image\ImageAnalyticsTagContext.js: Property body[6] of BlockStatement expected node to be of a type ["Statement"] but instead got "AssignmentExpression"

Any ideas?

**Comment by bghgary** [comment] 2021-08-04 22:47
Ideally, it would nice to get this to repro with a simple experience.js file in Babylon Native without React Native. That should make it easier to debug.

**Comment by star-collector** [comment] 2021-08-05 07:38
> I can't get this sample app to run. I get this error in the metro log:
> 
> > error: node_modules\react-native\Libraries\Image\ImageAnalyticsTagContext.js: Property body[6] of BlockStatement expected node to be of a type ["Statement"] but instead got "AssignmentExpression"
> 
> Any ideas?

I get this error too if I use npm to install packages. Try using Yarn. For some reason, npm install dependencies wrong, can't figure out why. Also, I updated my repo. There are no react-babylonjs anymore and it uses slightly modified App.tsx from your Playground app. Hopefully, it will help you with debugging. Here is new screenshot with absent character and occasional distortions. For some reason distortions depends on location of the camera. Sometimes they don't happen at all.

![Screenshot_20210805-103029_Playground](https://user-images.githubusercontent.com/19988178/128310809-f677773b-31f7-410b-ab98-17472963b051.jpg)

I used Highlight layer on all meshes, including the character.

**Comment by bghgary** [comment] 2021-08-05 16:57
I will try to repro, but curious if it repros without the highlight layer?

**Comment by star-collector** [comment] 2021-08-05 17:00
> I will try to repro, but curious if it repros without the highlight layer?

If I disable the highlight layer the character will still be transparent, however there will be no distortions. At least, I didn't notice any.

**Comment by darraghjburke** [comment] 2021-08-06 18:49
> > I will try to repro, but curious if it repros without the highlight layer?
> 
> If I disable the highlight layer the character will still be transparent, but there will be no distortions. At least, I didn't notice any. However, if a highlight layer added to at least one mesh visual artifacts will be back.

This repros on my Samsung S10+. Will investigate further

**Comment by bghgary** [comment] 2021-08-06 19:18
We have a bunch of devices and they all repro actually. I already spent a bunch of time looking at this. It has something do with the skinning. If I remove the skin, then it works, but I can't explain why it doesn't work with the skin yet. Will continue investigating.

@star-collector It would be helpful to know what device it works on. Can you list a few?

**Comment by star-collector** [comment] 2021-08-08 12:26
@bghgary Definetely works on HONOR 9X, HUAWEI P20 Pro and all Android emulators from Android Studio

**Comment by bghgary** [comment] 2021-08-13 00:36
I've been looking at this for a few days now with some help from @syntheticmagus. We are fairly certain we know what is going on now. Basically, we are running out of room for uniforms due to a high bone count. I am working on a fix, but there are a few things we need to do to fully fix this issue that I will document later. The short-term fix is to enable bone textures. I will probably blog about this bug next week to explain more.

**Comment by bghgary** [comment] 2021-08-17 00:36
This change will enable bone textures, which makes skins with many bones work correctly now.

https://github.com/BabylonJS/BabylonNative/pull/870

**Comment by star-collector** [comment] 2021-08-17 08:47
> This change will enable bone textures, which makes skins with many bones work correctly now.
> 
> [BabylonJS/BabylonNative#870](https://github.com/BabylonJS/BabylonNative/pull/870)

@ryantrem @bghgary Tried this and my app crashed. First I thought I build BabylonNative wrong or something, however crash reproduced after I installed recent @babylonjs/react-native package. It seems like all packages above 29 are broken.

**Comment by star-collector** [comment] 2021-08-17 09:00
Created new issue about this bug. https://github.com/BabylonJS/BabylonReactNative/issues/275

**Comment by bghgary** [comment] 2021-08-17 15:47
You will need a change on the Babylon.js side also which is building an npm right now.

**Comment by star-collector** [comment] 2021-08-17 15:50
> You will need a change on the Babylon.js side also which is building an npm right now.

I did change `@babylonjs/core/Engines/nativeEngine.js` according to your PR. However, my app crashes anyway.

**Comment by bghgary** [comment] 2021-08-17 15:51
What's the call stack?

**Comment by star-collector** [comment] 2021-08-17 15:54
> What's the call stack?

<img width="1750" alt="Screenshot 2021-08-17 at 18 54 11" src="https://user-images.githubusercontent.com/19988178/129759579-f1ef69d0-ad9e-4884-b274-1fafd36893e1.png">

**Comment by bghgary** [comment] 2021-08-17 15:58
Is this the one the repros without my changes?

**Comment by star-collector** [comment] 2021-08-17 16:01
> Is this the one that repros without my changes?

Yes, this isn't the first time I manually build npm package in this thread. I cloned BabylonReactNative, replaced BabylonNative submodule with your branch and later updated @babylonjs/core package according to your PR.

**Comment by bghgary** [comment] 2021-08-17 16:02
Let's put this info in the other issue you opened to avoid confusion :-)

**Comment by bghgary** [comment] 2021-08-17 16:29
I got it working in BabylonReactNative with my changes with this:
- Sync to master (b90a56e67496a71ad6b2f85520be689e672d163a)
- Run `npm install` from `Apps/Playground`
- Update `Modules/@babylonjs/react-native/submodules/BabylonNative` to my branch `better-texture-support`
- Changed `textureFloat = true` and `texture.format = format` in `Apps/Playground/node_modules/@babylonjs/core/Engines/nativeEngine.js`
- Changed `App.tsx` to load from `https://raw.githubusercontent.com/star-collector/babylon-playground/main/src/assets/models/base/blond.glb`

**Comment by star-collector** [comment] 2021-08-18 07:54
@bghgary It works! Thank you!

**Comment by star-collector** [comment] 2021-08-18 12:53
@bghgary Ok, noticed another thing. It seems like problematic phones and working phones have switched their places. Those phones which displayed models perfectly before now behave the same as problematic phones prior the update:

![Screenshot_20210818_154440_com zebrains digitalfriend](https://user-images.githubusercontent.com/19988178/129900556-4b342442-75b9-4ada-be1b-4b49330df7d2.jpg)

![Screenshot_20210818_154412_com zebrains digitalfriend](https://user-images.githubusercontent.com/19988178/129900810-8698c717-a4ad-4d47-b7e9-3dcb5b15db50.jpg)

These are screenshots from my HONOR 9X phone which didn't have problem with displaying models. Another problem exist on previously affected phones. Some character models are somewhat distorted. Their fingers and eyes are "wavy":

![Screenshot_20210818-154028_Uneed](https://user-images.githubusercontent.com/19988178/129901015-6a89bb06-fcc4-4df5-9096-5895fb0a7800.jpg)

**Comment by bghgary** [comment] 2021-08-18 17:30
That is weird. Can you list some phones where this is an issue?

**Comment by star-collector** [comment] 2021-08-18 17:51
> That is weird. Can you list some phones where this is an issue?

Disappearing characters: HONOR 9X, HUAWEI P20 Pro. Basically, pattern is reversed now.

Wavy fingers and eyes of male character model: Samsung Galaxy A71.

**Comment by bghgary** [comment] 2021-08-18 18:44
Ok, I'm going to have to see if we have those phones in the lab.

**Comment by bghgary** [comment] 2021-08-18 18:45
Hmm, doesn't look like we have either of those in the lab. Can you send me the Chrome about gpu info for these?

**Comment by bghgary** [comment] 2021-08-18 18:55
Are there any errors in logcat?

Can you also try this on these phones?
- Use Chrome to load this model with the Babylon.js sandbox, but disable Vulkan (`about://flags`, search for `Vulkan`, and disable it).

**Comment by ChocoPieLotte** [comment] 2021-08-19 07:08
Also i have wavy fingers and eyes of male character on Samsung Galaxy Note 20 ultra

**Comment by star-collector** [comment] 2021-08-19 08:40
> Hmm, doesn't look like we have either of those in the lab. Can you send me the Chrome about gpu info for these?

[honor9x.pdf](https://github.com/BabylonJS/BabylonReactNative/files/7012992/honor9x.pdf)
[huaweiP20Pro.pdf](https://github.com/BabylonJS/BabylonReactNative/files/7012993/huaweiP20Pro.pdf)

**Comment by star-collector** [comment] 2021-08-19 08:47
> Are there any errors in logcat?

No, there are no errors.

> Can you also try this on one of these phones?
> 
> * Use Chrome to load this model with the Babylon.js sandbox, but disable Vulkan (`about://flags`, search for `Vulkan`, and disable it).
>
> If this works, can you tell me the value of `BABYLON.Engine._caps.textureFloat`?

No, the bug does not reproduce. Model is being displayed without any problems with or without Vulkan.

**Comment by bghgary** [comment] 2021-08-19 18:00
I wrote a blog about this bug: https://babylonjs.medium.com/a-mysterious-case-of-skinned-mesh-disappearances-5fee23dd9cd6

> No, the bug does not reproduce. Model is being displayed without any problems with or without Vulkan.

I mean try this on a device that is not working (i.e. the issue is reproducing where the meshes disappear) with my changes and tell me the value of `BABYLON.Engine._caps.textureFloat`. I'm trying to figure out if bone textures are being used or not on these devices.

**Comment by star-collector** [comment] 2021-08-19 19:10
> I mean try this on a device that is not working (i.e. the issue is reproducing where the meshes disappear) with my changes and tell me the value of `BABYLON.Engine._caps.textureFloat`. I'm trying to figure out if bone textures are being used or not on these devices.

Ah, ok, sorry. The value of` BABYLON.Engine._caps.textureFloat` is `true` on my HONOR 9X.

**Comment by bghgary** [comment] 2021-08-19 19:27
Hehe, this is still not what mean :-)

I need to know this value when running in a browser. I have currently hard coded `BABYLON.Engine._caps.textureFloat` to be true for Babylon Native, but maybe these devices don't support float textures.

**Comment by star-collector** [comment] 2021-08-19 19:36
> I need to know this value when running in a browser. I have currently hard coded `BABYLON.Engine._caps.textureFloat` to be true for Babylon Native, but maybe these devices don't support float textures.

![Screenshot_20210819_223204_com android chrome](https://user-images.githubusercontent.com/19988178/130132918-4c565f00-48e4-421d-a4cc-fb7909bb58dd.jpg)

Value is `true `as well.

**Comment by bghgary** [comment] 2021-08-19 21:32
I need a repro to look into this more. I will try to find a device with similar/same GPU.

**Comment by bghgary** [comment] 2021-08-19 21:41
@star-collector Would you be willing/capable of using RenderDoc and capture a frame? I'm not totally sure a saved capture will transfer correctly, but we can give it a shot if you are willing.

**Comment by star-collector** [comment] 2021-08-20 09:40
> @star-collector Would you be willing/capable of using RenderDoc and capture a frame?

Sure, I'll try.

**Comment by star-collector** [comment] 2021-08-20 12:11
@bghgary You need just a rdc file, right? Here is one frame capture of my sample app, male character model, your BabylonNative branch.

https://drive.google.com/file/d/1go-BApl2uI1Cm0VTv6MAih2L3-DlVaqv/view?usp=sharing

**Comment by bghgary** [comment] 2021-08-20 16:32
Hmm, these two captures look identical in RenderDoc using local playback.

**Comment by bghgary** [comment] 2021-09-08 20:24
I'm back and it looks like we have "Samsung Galaxy Note 20 Ultra" devices in our lab, so I will be getting soon and try to repro.

**Comment by bghgary** [comment] 2021-09-10 17:40
@star-collector I think I misunderstood the list of devices. Are these devices that worked correctly before my changes and no longer work after my changes? I just loaded the `blond.glb` on a `Samsung Galaxy Note 20 Ultra` and it is working fine for me using the latest code.

**Comment by bghgary** [comment] 2021-09-10 17:44
@AAAkatov and @star-collector I need to repro the [new problem](https://github.com/babylonjs/babylonreactnative/issues/256#issuecomment-901089620) after my changes. Can you please let me know as many devices that repro with the latest code in Babylon Native so I can see if we have one of these devices in the lab?

**Comment by star-collector** [comment] 2021-09-10 20:48
@bghgary Me and my collegue @ChocoPieLotte rechecked `Samsung Galaxy Note 20 Ultra`. Apparently, this phone really does show characters with both 29 and 31 versions, however the reason it was reported to us as problematic is because characters are distorted with `alpha.31` as I reported some posts earlier:

>hese are screenshots from my HONOR 9X phone which didn't have problem with displaying models. Another problem exists on previously affected phones. Some character models are somewhat distorted. Their fingers and eyes are "wavy"

This is Note 20's screenshot with the `blond.glb` and `@babylonjs/react-native 0.4.0-alpha.31`. Note girl's lips.

![576cae85-8cc0-4551-8249-8219fd116093](https://user-images.githubusercontent.com/19988178/132914961-33612fb5-5a5b-418a-9cdd-eed332117689.jpg)

We'll try to find more phone models which do not display models with alpha.31.

**Comment by bghgary** [comment] 2021-09-10 22:28
I can't repro this problem with displaying models with the latest code in Babylon Native using a Samsung Galaxy Note 20 Ultra. I haven't tried Babylon React Native or using the npm packages.

**Comment by star-collector** [comment] 2021-09-13 09:58
Btw, we found another phone which has no problems displaying characters with alpha.29 and has transparent character meshes with alpha.31 or higher - REDMI 9.

**Comment by bghgary** [comment] 2021-09-15 20:43
I don't see REDMI 9 in the devices lab :(

I see @AAAkatov mentioned Pixel 4a which we have in the devices lab. Is this with alpha.31 or higher?

**Comment by star-collector** [comment] 2021-09-16 07:36
@bghgary No, Pixel 4a definitely had problems with alpha.29. I didn't check, but it should work OK with alpha.31. Though maybe it has deformed character bones/animations problem I mentioned above.

**Comment by bghgary** [comment] 2021-09-17 00:48
I figured out what is going on with the messed up fingers in the male model. We are somehow resetting the sampling mode for the bone texture back to linear when setting anisotropy. Using a bone texture sampled with linear will cause incorrect values to be sampled. We are guessing it works on some devices because they don't support linear sampling, but will fallback to nearest.

I'm not sure why we are resetting the sampling mode when setting anisotropy. I will discuss with @CedricGuillemet tomorrow. There is a high chance that this also fixes the disappearing case since linear texture filtering of RGBA32F textures are not supported on many devices. It may be that this causes the mesh to simply not draw at all instead of falling back.

@star-collector @AAAkatov et all, can someone build BabylonNative or BabylonReactNative from source and try something? This will be really helpful since I don't have a repro device.
1. Remove [these lines](https://github.com/BabylonJS/BabylonNative/blob/7552abc35c61bd016576ee286f499282e99767e5/Plugins/NativeEngine/Source/NativeEngine.cpp#L1464-L1469) from NativeEngine.cpp.
2. Change experience.js to load the problematic model.
3. Deploy to a device that reproduced the problem and see if the problem is gone.

Thanks!

**Comment by star-collector** [comment] 2021-09-17 08:09
@bghgary You are absolutely right! Removing these lines fixed both model deformations and transparent characters! At least, I didn't notice any problems with devices I have.

**Comment by bghgary** [comment] 2021-10-04 21:09
This should be fixed now in the latest drop. Please try it out and let us know!

**Closed** 2021-10-04 22:36 UTC
Labels: Android
