### ISSUE TITLE
Transparent background not working - scene.clearColor ignores alpha channel

### ISSUE THREAD

**Issue by swese44** [BabylonJS/BabylonReactNative#152] opened 2021-02-05 07:58 UTC
When setting `scene.clearColor`, `Color4`'s alpha channel is ignored. The background color is always the RGB values.

Basic example:

```ts
import { useEngine, EngineView } from "@babylonjs/react-native"
import {
  Scene,
  Camera,
  MeshBuilder,
  FreeCamera,
  Vector3,
  HemisphericLight,
  Color4,
} from "@babylonjs/core"
import React, { FC, useEffect, useState } from "react"

const engineStyle = { flex: 1, backgroundColor: "transparent" }

export const BabylonTest: FC = () => {
  const engine = useEngine()
  const [camera, setCamera] = useState<Camera>()

  const createScene = function () {
    const scene = new Scene(engine)
    scene.clearColor = new Color4(0, 0, 0, 0)
    const camera = new FreeCamera("camera1", new Vector3(0, 5, -10), scene)
    setCamera(camera)
    camera.setTarget(Vector3.Zero())
    const light = new HemisphericLight("light", new Vector3(0, 1, 0), scene)
    light.intensity = 0.7
    const sphere = MeshBuilder.CreateSphere("sphere", { diameter: 2, segments: 32 }, scene)
    sphere.position.y = 1
    const ground = MeshBuilder.CreateGround("ground", { width: 6, height: 6 }, scene)

    return scene
  }

  useEffect(() => {
    if (engine) {
      const scene = createScene()
    }
  }, [engine])

  return <EngineView style={engineStyle} camera={camera} />
}
```

<img width="374" alt="Screen Shot 2021-02-04 at 11 54 18 PM" src="https://user-images.githubusercontent.com/471731/107005548-b3635280-6744-11eb-953f-dacc6e7bbbbb.png">

**Comment by ryantrem** [comment] 2021-02-06 00:32
I've confirmed that setting `[super setOpaque:false];` in `EngineView`'s `init` fixes this on iOS.

On Android, in `EngineView`'s constructor I tried this:
```java
        this.setZOrderOnTop(true);
        this.getHolder().setFormat(PixelFormat.TRANSPARENT);
```
Which kind of works, but it makes it so that UI cannot be drawn on top of `EngineView`, which obvious breaks other scenarios. Needs a bit more investigation...

**Comment by ryantrem** [comment] 2021-02-06 18:29
I read up on this more and here's what I learned: there are two ways we can acquire a `Surface` to draw to on Android. The first is by using `SurfaceView`, which is what we do today. The way `SurfaceView` works is that it is actually provides a completely separate window to draw to. Normally a hole is punched through the parent window and the new window is aligned *behind* the parent window, which allows UI to be drawn on top of it. If you call `setZOrderOnTop(true)` then it is still a separate window, but is placed on top instead of behind. So with `SurfaceView`, all the UI is either on top of or behind the associated `Surface`. This makes it impossible to both have UI on top of it *and* behind it.

The alternative is `TextureView`, which is actually just a control in the regular UI hierarchy and can have UI behind it and on top of it at the same time. The way it works though is that you are basically rendering to a texture, and then the regular UI compositor composites it with the rest of the UI. Unfortunately what this means is that perceived performance is dictated by the regular UI compositor, which can be bad. This is different from `SurfaceView` which is fully rendered independently of the rest of the UI and therefore cannot be impacted by compositor performance.

The Android docs recommend preferring `SurfaceView` due to the potential perf impact of `TextureView`. Similarly, the iOS docs even say that setting `isOpaque` to false has performance implications. Given this, if we want to support transparency in `EngineView`, then I think we need to make that an explicit opt-in feature through a property like `isOpaque` or `allowTransparency` (e.g. `<EngineView isOpaque={false} />`). On the iOS side, this would just translate to setting the `isOpaque` property on the `MTKView` (as described earlier in this issue). On the Android side, `EngineView` would be a container view that contained either a `SurfaceView` (when transparency is not needed) or a `TextureView` (when transparency is needed).

Using `TextureView` is fairly similar to `SurfaceView`. We would create a `TextureView`, get a callback when the associated `SurfaceTexture` is created, and then construct a `Surface` from the `SurfaceTexture` (one of `Surface`'s constructors takes a `SurfaceTexture`), then just pass that `Surface` down to the native layers the same way we do with the `Surface` we get from the `SurfaceView`. I believe when we create the `Surface` ourselves, we also need to call `release` on that `Surface` when we are done with it (probably in the callback that tells us when the associated `SurfaceTexture` is destroyed).

**Comment by daenash** [comment] 2021-11-16 11:39
@ryantrem 

Hello! I'd just wanted to ask that is there any update regarding this issue? I'm currently trying to implement a transparent backgrounded babylon render and with the quickfix you [mentioned](https://github.com/BabylonJS/BabylonReactNative/issues/152#issuecomment-774360260) it sort-of works but unfortunately I have elements on top of that view so it's not really workable as that.

Thank you in advance!

**Comment by ryantrem** [comment] 2021-11-16 17:18
No, there has not been any progress on this issue. At this point, I think it will take some additional community contributions to get this change done. If you want to take a stab at implementing what I outlined above we'd be happy to have the contribution! 🙂

**Comment by daenash** [comment] 2021-11-18 14:11
@ryantrem 

I managed to implement the change for the transparent background for Android and iOS. So if you'd like to take a look at it just check the PR. 😌

**Comment by CedricGuillemet** [comment] 2022-01-24 12:29
closed via https://github.com/BabylonJS/BabylonReactNative/pull/314

**Closed** 2022-01-24 12:29 UTC
Labels: enhancement, help wanted
