### ISSUE TITLE
 Unable to load from glb/gltf file from url - Possible Unhandled Promise Rejection

### ISSUE THREAD

**Issue by krisidmisso** [BabylonJS/BabylonReactNative#482] opened 2022-10-13 02:02 UTC
**For questions, please use the [forum](https://forum.babylonjs.com)**.

**Describe the bug**
When using the sample code provided in https://github.com/BabylonJS/BabylonReactNativeSample/blob/main/App.tsx there is an error and the model doesn't load.
Tried the example app with RN 0.65.2 and also my app with RN 0.69.5

Android (undefined):
```
 LOG  BJS - [21:55:27]: Babylon Native (v5.27.1) launched
 WARN  Possible Unhandled Promise Rejection (id: 0):
RuntimeError: Unable to load from https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/BoxAnimated/glTF/BoxAnimated.gltf: LoadFileError: undefined is not a function
RuntimeError: Unable to load from https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/BoxAnimated/glTF/BoxAnimated.gltf: LoadFileError: undefined is not a function
    at construct (native)
    at Wrapper
```

iOS (this._xhr.getResponseHeader - related with https://github.com/BabylonJS/BabylonReactNative/issues/474 but there was a merge for the pull requests that fixed it):

```
 LOG  BJS - [22:31:22]: Babylon Native (v5.27.1) launched
 WARN  Possible Unhandled Promise Rejection (id: 0):
RuntimeError: Unable to load from https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/BoxAnimated/glTF/BoxAnimated.gltf: LoadFileError: this._xhr.getResponseHeader is not a function. (In 'this._xhr.getResponseHeader(name)', 'this._xhr.getResponseHeader' is undefined)
construct@[native code]
construct@[native code]
```

Error happens with SceneLoader.ImportMeshAsync.
I have `import '@babylonjs/loaders/glTF/2.0'` and also tried `import '@babylonjs/loaders';`

**To Reproduce**
1. Clone https://github.com/BabylonJS/BabylonReactNativeSample
2. See the error in console log

**Expected behavior**
The model should load async

**Screenshots**

**Other**
 - Platform: Android(Real device)/iOS (emulator)

**Comment by krisidmisso** [comment] 2022-10-13 16:30
UPDATE: for anyone having this issue checkout https://github.com/BabylonJS/BabylonReactNativeSample/issues/9#issuecomment-1271888679

Switching to versions 5.17.0 fixed the loading issue:
```
"@babylonjs/core": "5.17.0",
"@babylonjs/loaders": "5.17.0",
```

**Comment by bghgary** [comment] 2022-10-13 21:11
Yes, this is known. Fix is incoming. Dupe of #474.

**Closed by bghgary** 2022-10-13 21:11 UTC
