### ISSUE TITLE
Toggling EngineView on and off causes artifacting, and subsequent XR crashing

### ISSUE THREAD

**Issue by Alex-MSFT** [BabylonJS/BabylonReactNative#76] opened 2020-09-10 17:37 UTC
Toggling the engine view or engine screen visibility on and off in the playground app causes visual artifacting in the EngineView and subsequent attempts to launch XR mode to crash.

Repro steps:
1. Start the Playground app
2. Toggle engine view or engine screen off then on
3. Observe artifacting
4. Attempt to launch XR session
5. App will crash due to BadAccess when constructing the XR session

![IMG_0018](https://user-images.githubusercontent.com/27031140/92774100-ff56ca80-f351-11ea-867c-16f00b9c92e7.png)

![Screen Shot 2020-09-10 at 10 43 00 AM](https://user-images.githubusercontent.com/27031140/92774580-79874f00-f352-11ea-8b21-36edd2c0c4b0.png)

**Comment by ryantrem** [comment] 2020-09-11 17:15
Duplicate of #57

**Closed by ryantrem** 2020-09-11 17:15 UTC
