### ISSUE TITLE
PBR Rendering issues on Android v/s iOS

### ISSUE THREAD

**Issue by lokiiarora** [BabylonJS/BabylonReactNative#70] opened 2020-09-01 10:19 UTC
Asset used:
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/DamagedHelmet/glTF-Binary/DamagedHelmet.glb?raw=true

iOS Screenshot:
![Screenshot 2020-09-01 at 3 15 56 PM](https://user-images.githubusercontent.com/20043762/91838025-7c0aea00-ec6a-11ea-814b-51ed8dc7bb54.png)
Android Screenshot:
![Screenshot_20200901-152556](https://user-images.githubusercontent.com/20043762/91838079-904ee700-ec6a-11ea-8e78-57f9611cd299.jpg)
![Screenshot_20200901-152530](https://user-images.githubusercontent.com/20043762/91838108-9644c800-ec6a-11ea-9498-c29755de5c00.jpg)

Devices Used:
Android: GM1901 Oneplus 7
iOS: iPhone 11 iOS 13.3

**Comment by bghgary** [comment] 2020-09-18 20:02
This is a dupe of https://github.com/BabylonJS/BabylonNative/issues/385

**Closed by bghgary** 2020-09-18 20:02 UTC
